language: java
dist: trusty
jdk: oraclejdk8
script: ant junit compile
deploy:
  provider: releases
  api_key: "2da0ed03b6938cc45a1645f8a580fbeafdf7e513"
  file: "build/lib/axis.jar"
  skip_cleanup: true
  draft: true